version: '3'
services:
    customer-portal:
        container_name: customer-portal
        build: .
        ports:
            - "5002:5002"
            - "35729:35729"
        networks:
            - do-portal-net
networks:
    do-portal-net:
        external: true
