version: '3.5'
services:
    db:
        image: postgres:9.6-alpine
        container_name: cert_db
        environment:
            POSTGRES_USER: do_portal
            POSTGRES_PASSWORD: do_portal
            POSTGRES_DB: do_portal
        volumes:
            - db_data:/var/lib/postgresql/data
        networks:
            - do-portal-net
    do-portal:
        container_name: do-portal
        build: .
        ports:
            - "5001:5001"
        networks:
            - do-portal-net
volumes:
    db_data:

networks:
    do-portal-net:
        name: do-portal-net
        driver: bridge
